### ISSUE TITLE
Missing AceTime.h

### ISSUE THREAD

**Issue by hwdornbush** [wfdudley/T-watch-2020#12]
When I tried to compile, I got an error message.  I also got a bunch of Multiple Libraries warnings.  I suspect the multiple libraries were due to my trying to install other versions of the watch programs.  I can delete the multiple libraries but where do I get the AceTime.h?

Arduino: 1.8.10 (Windows 10), Board: "TTGO T-Watch, Enabled, Default (2 x 6.5 MB app, 3.6 MB SPIFFS), 2000000, None"

DudleyWatch:26:21: error: AceTime.h: No such file or directory

compilation terminated.

Multiple libraries were found for "SPIFFS.h"
 Used: C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\SPIFFS
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
 Not used: C:\Program
Multiple libraries were found for "LilyGoWatch.h"
 Used: C:\Users\Bill\Documents\Arduino\libraries\TTGO_TWatch_Library-master
Multiple libraries were found for "SPI.h"
 Used: C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\SPI
Multiple libraries were found for "Ticker.h"
 Used: C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Ticker
Multiple libraries were found for "Wire.h"
 Used: C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire
Multiple libraries were found for "FS.h"
 Used: C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\FS
exit status 1
AceTime.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by wfdudley** [comment]
You need the AceTime library.  This pre-requisite is the first thing in the README.md file.
