### ISSUE TITLE
'MY_LANGUAGE' was not declared in this scope

### ISSUE THREAD

**Issue by hwdornbush** [wfdudley/T-watch-2020#14]
I got the above error message when I tried to upload the version which I downloaded on 12/23/2020.  How can I resolve this?

Error messages log:

Arduino: 1.8.13 (Windows 10), Board: "TTGO T-Watch, Enabled, Default (2 x 6.5 MB app, 3.6 MB SPIFFS), 2000000, None"

In file included from C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\cores\esp32/WString.h:29:0,

                 from C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\cores\esp32/Arduino.h:146,

                 from sketch\DudleyWatch.ino.cpp:1:

C:\Users\Bill\Documents\Arduino\DudleyWatch\DudleyWatch.ino: In function 'void setup()':

DudleyWatch:240:44: error: 'MY_LANGUAGE' was not declared in this scope

     strcpy_P(general_config.language, PSTR(MY_LANGUAGE));

                                            ^

C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\cores\esp32/pgmspace.h:35:24: note: in definition of macro 'PSTR'

 #define PSTR(s)       (s)

                        ^

Multiple libraries were found for "WiFi.h"

 Used: C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi

 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi

Multiple libraries were found for "SD.h"

 Used: C:\Users\Bill\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\SD

 Not used: C:\Program Files (x86)\Arduino\libraries\SD

exit status 1

'MY_LANGUAGE' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by wfdudley** [comment]
Added:

#define MY_LANGUAGE "en"

to personal_info.h

language feature is not supported "yet".
