### ISSUE TITLE
Not a issue but I'm from where you are from.

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [wfdudley/T-watch-2020#17]
Just wanted to say hello. I'm testing your code out looks awesome.

Joseph

P.s I'm from Trenton lol.

**Comment by wfdudley** [comment]
Thanks for your kind comment.  I wonder if there's a better medium for fan mail than raising Github issues?

**Comment by genotix** [comment]
Lol 🤣


Met vriendelijke groet / Kind regards,

Eric Oud Ammerveld
Phone:
+31 10 495 19 55
Mobile:
+31 6 55 86 25 44
E-mail:
eric@genotix.nl
