### ISSUE TITLE
get_location.cpp doesn't compile

### ISSUE THREAD

**Issue by FedericoBusero** [wfdudley/T-watch-2020#26]
```
sketch\get_location.cpp: In function 'int get_city_from_lat_long(char*, char*)':
get_location.cpp:168:94: error: 'LOCATIONIQ_KEY' was not declared in this scope
   sprintf(url, "https://us1.locationiq.com/v1/reverse.php?key=%s&format=json&lat=%s&lon=%s", LOCATIONIQ_KEY, latitude, longitude);
```
...

`'LOCATIONIQ_KEY' was not declared in this scope`

**Comment by wfdudley** [comment]
add this line to personal_info.h:

#define LOCATIONIQ_KEY ""

I can't make the mod now, busy with real work.

Thanks,
Bill Dudley

This email is free of malware because I run Linux.

**Comment by wfdudley** [comment]
I made the change to personal_info.h

dud

This email is free of malware because I run Linux.

**Comment by FedericoBusero** [comment]
Thanks!
